// Static forge recipe data extracted from the NotEnoughUpdates item repo.
// Forge recipes change only on major game updates - regenerate from NEU if needed.

export interface ForgeRecipe {
  id: string
  name: string
  duration: number      // seconds for one forge run
  count: number         // output quantity per run
  hotm: number | null   // Heart of the Mountain tier required
  inputs: Array<{ id: string; qty: number }>
}

export const FORGE_RECIPES: ForgeRecipe[] = [
  { id: 'AMBER_MATERIAL', name: 'Amber Material', duration: 21600, count: 1, hotm: 6, inputs: [{ id: 'GOLDEN_PLATE', qty: 1 }, { id: 'FINE_AMBER_GEM', qty: 12 }] },
  { id: 'AMBER_NECKLACE', name: 'Amber Necklace', duration: 86400, count: 1, hotm: 5, inputs: [{ id: 'GLOSSY_GEMSTONE', qty: 32 }, { id: 'FLAWLESS_AMBER_GEM', qty: 2 }] },
  { id: 'AMBER_POLISHED_DRILL_ENGINE', name: 'Amber-Polished Drill Engine', duration: 30, count: 1, hotm: 9, inputs: [{ id: 'DRILL_ENGINE', qty: 5 }, { id: 'PERFECT_AMBER_GEM', qty: 5 }, { id: 'PRECURSOR_APPARATUS', qty: 16 }, { id: 'SAPPHIRE_POLISHED_DRILL_ENGINE', qty: 1 }, { id: 'PLASMA', qty: 32 }] },
  { id: 'AMETHYST_GAUNTLET', name: 'Amethyst Gauntlet', duration: 86400, count: 1, hotm: 5, inputs: [{ id: 'GLOSSY_GEMSTONE', qty: 32 }, { id: 'FLAWLESS_AMETHYST_GEM', qty: 2 }] },
  { id: 'AMMONITE;4', name: '[Lvl {LVL}] Ammonite', duration: 259200, count: 1, hotm: 4, inputs: [{ id: 'HELIX', qty: 1 }, { id: 'SKYBLOCK_COIN', qty: 300000 }] },
  { id: 'ANKYLOSAURUS;4', name: '[Lvl {LVL}] Ankylosaurus', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'FLAWLESS_OPAL_GEM', qty: 1 }, { id: 'CLUBBED_FOSSIL', qty: 1 }] },
  { id: 'BASE_CAMP_TRAVEL_SCROLL', name: 'Travel Scroll to the Dwarven Base Camp', duration: 36000, count: 1, hotm: null, inputs: [{ id: 'SKYBLOCK_COIN', qty: 500000 }, { id: 'FLAWLESS_ONYX_GEM', qty: 1 }, { id: 'ENCHANTED_ENDER_PEARL', qty: 16 }] },
  { id: 'BEACON_2', name: 'Beacon II', duration: 72000, count: 1, hotm: 2, inputs: [{ id: 'REFINED_MITHRIL', qty: 5 }, { id: 'BEACON_1', qty: 1 }] },
  { id: 'BEACON_3', name: 'Beacon III', duration: 108000, count: 1, hotm: 3, inputs: [{ id: 'REFINED_MITHRIL', qty: 10 }, { id: 'BEACON_2', qty: 1 }] },
  { id: 'BEACON_4', name: 'Beacon IV', duration: 144000, count: 1, hotm: 4, inputs: [{ id: 'REFINED_MITHRIL', qty: 20 }, { id: 'BEACON_3', qty: 1 }, { id: 'PLASMA', qty: 1 }] },
  { id: 'BEACON_5', name: 'Beacon V', duration: 180000, count: 1, hotm: 5, inputs: [{ id: 'BEACON_4', qty: 1 }, { id: 'REFINED_MITHRIL', qty: 40 }, { id: 'PLASMA', qty: 5 }] },
  { id: 'BEJEWELED_COLLAR', name: 'Bejeweled Collar', duration: 7200, count: 1, hotm: 2, inputs: [{ id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'REFINED_MITHRIL', qty: 4 }] },
  { id: 'BEJEWELED_HANDLE', name: 'Bejeweled Handle', duration: 30, count: 1, hotm: 2, inputs: [{ id: 'GLACITE_JEWEL', qty: 3 }] },
  { id: 'CRYSTAL_HOLLOWS_TRAVEL_SCROLL', name: 'Travel Scroll to the Crystal Hollows', duration: 36000, count: 1, hotm: null, inputs: [{ id: 'FLAWED_RUBY_GEM', qty: 48 }, { id: 'SKYBLOCK_COIN', qty: 50000 }, { id: 'ENCHANTED_ENDER_PEARL', qty: 16 }, { id: 'FINE_RUBY_GEM', qty: 80 }] },
  { id: 'DIAMONITE', name: 'Diamonite', duration: 21600, count: 1, hotm: 2, inputs: [{ id: 'REFINED_DIAMOND', qty: 3 }] },
  { id: 'DIVAN_BOOTS', name: 'Boots of Divan', duration: 86400, count: 1, hotm: 6, inputs: [{ id: 'GEMSTONE_MIXTURE', qty: 10 }, { id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'DIVAN_FRAGMENT', qty: 4 }] },
  { id: 'DIVAN_CHESTPLATE', name: 'Chestplate of Divan', duration: 86400, count: 1, hotm: 6, inputs: [{ id: 'GEMSTONE_MIXTURE', qty: 10 }, { id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'DIVAN_FRAGMENT', qty: 8 }] },
  { id: 'DIVAN_DRILL', name: 'Divan\'s Drill', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'TITANIUM_DRILL_4', qty: 1 }, { id: 'SKYBLOCK_COIN', qty: 50000000 }, { id: 'DIVAN_ALLOY', qty: 1 }] },
  { id: 'DIVAN_HELMET', name: 'Helmet of Divan', duration: 86400, count: 1, hotm: 6, inputs: [{ id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'GEMSTONE_MIXTURE', qty: 10 }, { id: 'DIVAN_FRAGMENT', qty: 5 }] },
  { id: 'DIVAN_LEGGINGS', name: 'Leggings of Divan', duration: 86400, count: 1, hotm: 6, inputs: [{ id: 'DIVAN_FRAGMENT', qty: 7 }, { id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'GEMSTONE_MIXTURE', qty: 10 }] },
  { id: 'DIVAN_PENDANT', name: 'Pendant of Divan', duration: 604800, count: 1, hotm: 10, inputs: [{ id: 'PERFECT_PLATE', qty: 1 }, { id: 'DIVAN_FRAGMENT', qty: 10 }, { id: 'SHATTERED_PENDANT', qty: 1 }] },
  { id: 'DIVAN_POWDER_COATING', name: 'Divan\'s Powder Coating', duration: 129600, count: 1, hotm: 4, inputs: [{ id: 'REFINED_MINERAL', qty: 32 }, { id: 'GLOSSY_GEMSTONE', qty: 32 }, { id: 'ENCHANTED_GOLD_BLOCK', qty: 16 }, { id: 'DIVAN_FRAGMENT', qty: 5 }] },
  { id: 'DRILL_ENGINE', name: 'Drill Motor', duration: 108000, count: 1, hotm: 3, inputs: [{ id: 'ENCHANTED_IRON_BLOCK', qty: 1 }, { id: 'ENCHANTED_REDSTONE_BLOCK', qty: 3 }, { id: 'TREASURITE', qty: 10 }, { id: 'GOLDEN_PLATE', qty: 1 }] },
  { id: 'DWARVEN_HANDWARMERS', name: 'Dwarven Handwarmers', duration: 14400, count: 1, hotm: 8, inputs: [{ id: 'FLAWLESS_JADE_GEM', qty: 1 }, { id: 'UMBER_PLATE', qty: 1 }, { id: 'FLAWLESS_AMBER_GEM', qty: 1 }, { id: 'TUNGSTEN_PLATE', qty: 1 }] },
  { id: 'DWARVEN_METAL', name: 'Dwarven Metal Talisman', duration: 86400, count: 1, hotm: 8, inputs: [{ id: 'REFINED_TUNGSTEN', qty: 4 }, { id: 'REFINED_UMBER', qty: 4 }, { id: 'GLACITE_AMALGAMATION', qty: 4 }] },
  { id: 'FORGE_TRAVEL_SCROLL', name: 'Travel Scroll to the Dwarven Forge', duration: 18000, count: 1, hotm: 2, inputs: [{ id: 'SKYBLOCK_COIN', qty: 25000 }, { id: 'ENCHANTED_ENDER_PEARL', qty: 16 }, { id: 'MITHRIL_ORE', qty: 48 }, { id: 'TITANIUM_ORE', qty: 80 }] },
  { id: 'FRIGID_HUSK', name: 'Frigid Husk', duration: 21600, count: 1, hotm: 7, inputs: [{ id: 'FLAWLESS_ONYX_GEM', qty: 1 }, { id: 'GLACITE_AMALGAMATION', qty: 4 }] },
  { id: 'FUEL_TANK', name: 'Fuel Canister', duration: 36000, count: 1, hotm: 2, inputs: [{ id: 'ENCHANTED_COAL_BLOCK', qty: 2 }] },
  { id: 'GEMSTONE_CHAMBER', name: 'Gemstone Chamber', duration: 14400, count: 1, hotm: 5, inputs: [{ id: 'WORM_MEMBRANE', qty: 100 }, { id: 'GEMSTONE_MIXTURE', qty: 1 }, { id: 'SKYBLOCK_COIN', qty: 25000 }] },
  { id: 'GEMSTONE_DRILL_1', name: 'Ruby Drill TX-15', duration: 14400, count: 1, hotm: 4, inputs: [{ id: 'DRILL_ENGINE', qty: 1 }, { id: 'FUEL_TANK', qty: 1 }, { id: 'FINE_RUBY_GEM', qty: 6 }] },
  { id: 'GEMSTONE_DRILL_2', name: 'Gemstone Drill LT-522', duration: 30, count: 1, hotm: 4, inputs: [{ id: 'GEMSTONE_DRILL_1', qty: 1 }, { id: 'GEMSTONE_MIXTURE', qty: 3 }] },
  { id: 'GEMSTONE_DRILL_3', name: 'Topaz Drill KGR-12', duration: 30, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_TOPAZ_GEM', qty: 1 }, { id: 'GEMSTONE_MIXTURE', qty: 3 }, { id: 'GEMSTONE_DRILL_2', qty: 1 }, { id: 'MAGMA_CORE', qty: 8 }] },
  { id: 'GEMSTONE_DRILL_4', name: 'Jasper Drill X', duration: 30, count: 1, hotm: 6, inputs: [{ id: 'TREASURITE', qty: 100 }, { id: 'FLAWLESS_JASPER_GEM', qty: 1 }, { id: 'GEMSTONE_DRILL_3', qty: 1 }, { id: 'MAGMA_CORE', qty: 16 }] },
  { id: 'GEMSTONE_FUEL_TANK', name: 'Gemstone Fuel Tank', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'GEMSTONE_MIXTURE', qty: 10 }, { id: 'TITANIUM_FUEL_TANK', qty: 1 }, { id: 'PRECURSOR_APPARATUS', qty: 4 }] },
  { id: 'GEMSTONE_MIXTURE', name: 'Gemstone Mixture', duration: 14400, count: 1, hotm: 4, inputs: [{ id: 'FINE_JADE_GEM', qty: 4 }, { id: 'SLUDGE_JUICE', qty: 320 }, { id: 'FINE_AMBER_GEM', qty: 4 }, { id: 'FINE_SAPPHIRE_GEM', qty: 4 }, { id: 'FINE_AMETHYST_GEM', qty: 4 }] },
  { id: 'GLACITE_AMALGAMATION', name: 'Glacite Amalgamation', duration: 14400, count: 1, hotm: 7, inputs: [{ id: 'ENCHANTED_GLACITE', qty: 256 }, { id: 'FINE_PERIDOT_GEM', qty: 4 }, { id: 'FINE_AQUAMARINE_GEM', qty: 4 }, { id: 'FINE_CITRINE_GEM', qty: 4 }, { id: 'FINE_ONYX_GEM', qty: 4 }] },
  { id: 'GLACITE_CHISEL', name: 'Glacite-Plated Chisel', duration: 30, count: 1, hotm: 9, inputs: [{ id: 'REINFORCED_CHISEL', qty: 1 }, { id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'GLACITE_AMALGAMATION', qty: 8 }, { id: 'MITHRIL_PLATE', qty: 1 }] },
  { id: 'GLACITE_LANTERN', name: 'Glacite Lantern', duration: 43200, count: 1, hotm: 8, inputs: [{ id: 'TITANIUM_LANTERN', qty: 1 }, { id: 'GLACITE_AMALGAMATION', qty: 4 }, { id: 'ENCHANTED_EMERALD_BLOCK', qty: 2 }] },
  { id: 'GLEAMING_CRYSTAL', name: 'Gleaming Crystal', duration: 21600, count: 1, hotm: 4, inputs: [{ id: 'GLOSSY_GEMSTONE', qty: 32 }, { id: 'REFINED_MITHRIL', qty: 1 }, { id: 'REFINED_DIAMOND', qty: 2 }] },
  { id: 'GOBLIN;4', name: '[Lvl {LVL}] Goblin', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'FLAWLESS_AMBER_GEM', qty: 1 }, { id: 'UGLY_FOSSIL', qty: 1 }] },
  { id: 'GOBLIN_OMELETTE', name: 'Goblin Omelette', duration: 64800, count: 1, hotm: 3, inputs: [{ id: 'GOBLIN_EGG', qty: 96 }] },
  { id: 'GOBLIN_OMELETTE_BLUE_CHEESE', name: 'Blue Cheese Goblin Omelette', duration: 64800, count: 1, hotm: 5, inputs: [{ id: 'GOBLIN_OMELETTE', qty: 1 }, { id: 'FLAWLESS_SAPPHIRE_GEM', qty: 1 }, { id: 'GOBLIN_EGG_BLUE', qty: 96 }] },
  { id: 'GOBLIN_OMELETTE_PESTO', name: 'Pesto Goblin Omelette', duration: 64800, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_JADE_GEM', qty: 1 }, { id: 'GOBLIN_EGG_GREEN', qty: 96 }, { id: 'GOBLIN_OMELETTE', qty: 1 }] },
  { id: 'GOBLIN_OMELETTE_SPICY', name: 'Spicy Goblin Omelette', duration: 64800, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'GOBLIN_OMELETTE', qty: 1 }, { id: 'GOBLIN_EGG_RED', qty: 96 }] },
  { id: 'GOBLIN_OMELETTE_SUNNY_SIDE', name: 'Sunny Side Goblin Omelette', duration: 64800, count: 1, hotm: 5, inputs: [{ id: 'GOBLIN_EGG_YELLOW', qty: 96 }, { id: 'FLAWLESS_TOPAZ_GEM', qty: 1 }, { id: 'GOBLIN_OMELETTE', qty: 1 }] },
  { id: 'GOLDEN_PLATE', name: 'Golden Plate', duration: 21600, count: 1, hotm: 2, inputs: [{ id: 'ENCHANTED_GOLD_BLOCK', qty: 2 }, { id: 'REFINED_DIAMOND', qty: 1 }, { id: 'GLACITE_JEWEL', qty: 5 }] },
  { id: 'HOT_STUFF', name: 'Scorched Topaz', duration: 21600, count: 1, hotm: 4, inputs: [{ id: 'FLAWLESS_TOPAZ_GEM', qty: 1 }, { id: 'ENCHANTED_HARD_STONE', qty: 128 }] },
  { id: 'JADE_BELT', name: 'Jade Belt', duration: 86400, count: 1, hotm: 5, inputs: [{ id: 'GLOSSY_GEMSTONE', qty: 32 }, { id: 'FLAWLESS_JADE_GEM', qty: 2 }] },
  { id: 'MAMMOTH;4', name: '[Lvl {LVL}] Mammoth', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'TUSK_FOSSIL', qty: 1 }, { id: 'FLAWLESS_ONYX_GEM', qty: 1 }] },
  { id: 'MITHRIL_BELT', name: 'Mithril Belt', duration: 3600, count: 1, hotm: 1, inputs: [{ id: 'ENCHANTED_MITHRIL', qty: 3 }] },
  { id: 'MITHRIL_CLOAK', name: 'Mithril Cloak', duration: 3600, count: 1, hotm: 1, inputs: [{ id: 'ENCHANTED_MITHRIL', qty: 3 }] },
  { id: 'MITHRIL_DRILL_1', name: 'Mithril Drill SX-R226', duration: 14400, count: 1, hotm: 2, inputs: [{ id: 'REFINED_MITHRIL', qty: 3 }, { id: 'DRILL_ENGINE', qty: 1 }, { id: 'FUEL_TANK', qty: 1 }] },
  { id: 'MITHRIL_DRILL_2', name: 'Mithril Drill SX-R326', duration: 30, count: 1, hotm: 3, inputs: [{ id: 'GOLDEN_PLATE', qty: 1 }, { id: 'MITHRIL_DRILL_1', qty: 1 }, { id: 'MITHRIL_PLATE', qty: 1 }] },
  { id: 'MITHRIL_DRILL_ENGINE', name: 'Mithril-Plated Drill Engine', duration: 86400, count: 1, hotm: 3, inputs: [{ id: 'MITHRIL_PLATE', qty: 1 }, { id: 'DRILL_ENGINE', qty: 2 }] },
  { id: 'MITHRIL_FUEL_TANK', name: 'Mithril-Infused Fuel Tank', duration: 86400, count: 1, hotm: 3, inputs: [{ id: 'REFINED_DIAMOND', qty: 5 }, { id: 'REFINED_MITHRIL', qty: 10 }, { id: 'FUEL_TANK', qty: 5 }] },
  { id: 'MITHRIL_GAUNTLET', name: 'Mithril Gauntlet', duration: 3600, count: 1, hotm: 1, inputs: [{ id: 'ENCHANTED_MITHRIL', qty: 3 }] },
  { id: 'MITHRIL_LANTERN', name: 'Mithril Lantern', duration: 1800, count: 1, hotm: 2, inputs: [{ id: 'LANTERN', qty: 1 }, { id: 'REFINED_MITHRIL', qty: 1 }, { id: 'ENCHANTED_EMERALD', qty: 16 }] },
  { id: 'MITHRIL_NECKLACE', name: 'Mithril Necklace', duration: 3600, count: 1, hotm: 1, inputs: [{ id: 'ENCHANTED_MITHRIL', qty: 3 }] },
  { id: 'MITHRIL_PLATE', name: 'Mithril Plate', duration: 64800, count: 1, hotm: 3, inputs: [{ id: 'GOLDEN_PLATE', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 1 }, { id: 'REFINED_MITHRIL', qty: 5 }, { id: 'ENCHANTED_IRON_BLOCK', qty: 1 }] },
  { id: 'MOLE;4', name: '[Lvl {LVL}] Mole', duration: 259200, count: 1, hotm: 4, inputs: [{ id: 'SKYBLOCK_COIN', qty: 300000 }, { id: 'CLAW_FOSSIL', qty: 1 }] },
  { id: 'PENGUIN;4', name: '[Lvl {LVL}] Penguin', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'WEBBED_FOSSIL', qty: 1 }, { id: 'FLAWLESS_AQUAMARINE_GEM', qty: 1 }] },
  { id: 'PERFECTLY_CUT_FUEL_TANK', name: 'Perfectly-Cut Fuel Tank', duration: 30, count: 1, hotm: 8, inputs: [{ id: 'GEMSTONE_FUEL_TANK', qty: 1 }, { id: 'PRECURSOR_APPARATUS', qty: 16 }, { id: 'GEMSTONE_MIXTURE', qty: 25 }, { id: 'PLASMA', qty: 32 }] },
  { id: 'PERFECT_AMBER_GEM', name: '⸕ Perfect Amber Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'AMBER_CRYSTAL', qty: 1 }, { id: 'FLAWLESS_AMBER_GEM', qty: 5 }] },
  { id: 'PERFECT_AMETHYST_GEM', name: '❈ Perfect Amethyst Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'AMETHYST_CRYSTAL', qty: 1 }, { id: 'FLAWLESS_AMETHYST_GEM', qty: 5 }] },
  { id: 'PERFECT_AQUAMARINE_GEM', name: '☂ Perfect Aquamarine Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'AQUAMARINE_CRYSTAL', qty: 1 }, { id: 'FLAWLESS_AQUAMARINE_GEM', qty: 5 }] },
  { id: 'PERFECT_CHISEL', name: 'Perfect Chisel', duration: 30, count: 1, hotm: 10, inputs: [{ id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'GLACITE_CHISEL', qty: 1 }, { id: 'PERFECT_PLATE', qty: 1 }] },
  { id: 'PERFECT_CITRINE_GEM', name: '☘ Perfect Citrine Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_CITRINE_GEM', qty: 5 }, { id: 'CITRINE_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_JADE_GEM', name: '☘ Perfect Jade Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_JADE_GEM', qty: 5 }, { id: 'JADE_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_JASPER_GEM', name: '❁ Perfect Jasper Gemstone', duration: 72000, count: 1, hotm: null, inputs: [{ id: 'FLAWLESS_JASPER_GEM', qty: 5 }, { id: 'JASPER_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_ONYX_GEM', name: '☠ Perfect Onyx Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_ONYX_GEM', qty: 5 }, { id: 'ONYX_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_OPAL_GEM', name: '❂ Perfect Opal Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_OPAL_GEM', qty: 5 }, { id: 'OPAL_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_PERIDOT_GEM', name: '☘ Perfect Peridot Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'PERIDOT_CRYSTAL', qty: 1 }, { id: 'FLAWLESS_PERIDOT_GEM', qty: 5 }] },
  { id: 'PERFECT_PLATE', name: 'Perfect Plate', duration: 1800, count: 1, hotm: 10, inputs: [{ id: 'UMBER_PLATE', qty: 1 }, { id: 'TUNGSTEN_PLATE', qty: 1 }, { id: 'MITHRIL_PLATE', qty: 1 }] },
  { id: 'PERFECT_RUBY_GEM', name: '❤ Perfect Ruby Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'RUBY_CRYSTAL', qty: 1 }, { id: 'FLAWLESS_RUBY_GEM', qty: 5 }] },
  { id: 'PERFECT_SAPPHIRE_GEM', name: '✎ Perfect Sapphire Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_SAPPHIRE_GEM', qty: 5 }, { id: 'SAPPHIRE_CRYSTAL', qty: 1 }] },
  { id: 'PERFECT_TOPAZ_GEM', name: '✧ Perfect Topaz Gemstone', duration: 72000, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_TOPAZ_GEM', qty: 5 }, { id: 'TOPAZ_CRYSTAL', qty: 1 }] },
  { id: 'PETRIFIED_STARFALL', name: 'Petrified Starfall', duration: 21600, count: 1, hotm: 3, inputs: [{ id: 'STARFALL', qty: 512 }] },
  { id: 'POCKET_ICEBERG', name: 'Pocket Iceberg', duration: 21600, count: 1, hotm: 2, inputs: [{ id: 'GLACITE_JEWEL', qty: 5 }] },
  { id: 'POLISHED_TOPAZ_ROD', name: 'Topaz Rod', duration: 43200, count: 1, hotm: 5, inputs: [{ id: 'BEJEWELED_HANDLE', qty: 3 }, { id: 'FLAWLESS_TOPAZ_GEM', qty: 2 }] },
  { id: 'PORTABLE_CAMPFIRE', name: 'Portable Campfire', duration: 1800, count: 1, hotm: 8, inputs: [{ id: 'REFINED_UMBER', qty: 1 }, { id: 'MATCH_STICKS', qty: 16 }] },
  { id: 'POWER_CRYSTAL', name: 'Power Crystal', duration: 7200, count: 1, hotm: 2, inputs: [{ id: 'STARFALL', qty: 256 }] },
  { id: 'POWER_RELIC', name: 'Relic of Power', duration: 28800, count: 1, hotm: 10, inputs: [{ id: 'POWER_ARTIFACT', qty: 1 }, { id: 'PERFECT_PLATE', qty: 1 }, { id: 'GLACITE_AMALGAMATION', qty: 32 }] },
  { id: 'PURE_MITHRIL', name: 'Pure Mithril', duration: 21600, count: 1, hotm: 3, inputs: [{ id: 'REFINED_MITHRIL', qty: 2 }] },
  { id: 'REFINED_DIAMOND', name: 'Refined Diamond', duration: 28800, count: 1, hotm: 2, inputs: [{ id: 'ENCHANTED_DIAMOND_BLOCK', qty: 2 }] },
  { id: 'REFINED_MITHRIL', name: 'Refined Mithril', duration: 21600, count: 1, hotm: 2, inputs: [{ id: 'ENCHANTED_MITHRIL', qty: 160 }] },
  { id: 'REFINED_TITANIUM', name: 'Refined Titanium', duration: 43200, count: 1, hotm: 2, inputs: [{ id: 'ENCHANTED_TITANIUM', qty: 16 }] },
  { id: 'REFINED_TUNGSTEN', name: 'Refined Tungsten', duration: 3600, count: 1, hotm: 7, inputs: [{ id: 'ENCHANTED_TUNGSTEN', qty: 160 }] },
  { id: 'REFINED_UMBER', name: 'Refined Umber', duration: 3600, count: 1, hotm: 7, inputs: [{ id: 'ENCHANTED_UMBER', qty: 160 }] },
  { id: 'REINFORCED_CHISEL', name: 'Reinforced Chisel', duration: 30, count: 1, hotm: 8, inputs: [{ id: 'REFINED_TUNGSTEN', qty: 2 }, { id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'REFINED_UMBER', qty: 2 }, { id: 'CHISEL', qty: 1 }] },
  { id: 'ROCK_GEMSTONE', name: 'Dwarven Geode', duration: 21600, count: 1, hotm: 3, inputs: [{ id: 'TREASURITE', qty: 64 }, { id: 'ENCHANTED_COBBLESTONE', qty: 128 }] },
  { id: 'RUBY_POLISHED_DRILL_ENGINE', name: 'Ruby-Polished Drill Engine', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'PERFECT_RUBY_GEM', qty: 1 }, { id: 'PRECURSOR_APPARATUS', qty: 4 }, { id: 'TITANIUM_DRILL_ENGINE', qty: 1 }, { id: 'DRILL_ENGINE', qty: 5 }] },
  { id: 'SAPPHIRE_CLOAK', name: 'Sapphire Cloak', duration: 86400, count: 1, hotm: 5, inputs: [{ id: 'FLAWLESS_SAPPHIRE_GEM', qty: 2 }, { id: 'GLOSSY_GEMSTONE', qty: 32 }] },
  { id: 'SAPPHIRE_POLISHED_DRILL_ENGINE', name: 'Sapphire-Polished Drill Engine', duration: 30, count: 1, hotm: 8, inputs: [{ id: 'PERFECT_SAPPHIRE_GEM', qty: 3 }, { id: 'DRILL_ENGINE', qty: 5 }, { id: 'RUBY_POLISHED_DRILL_ENGINE', qty: 1 }, { id: 'PLASMA', qty: 16 }, { id: 'PRECURSOR_APPARATUS', qty: 8 }] },
  { id: 'SECRET_RAILROAD_PASS', name: 'Secret Railroad Pass', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'CORLEONITE', qty: 8 }, { id: 'REFINED_MITHRIL', qty: 2 }, { id: 'FLAWLESS_RUBY_GEM', qty: 1 }] },
  { id: 'SKELETON_KEY', name: 'Skeleton Key', duration: 1800, count: 1, hotm: 10, inputs: [{ id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'PERFECT_PLATE', qty: 1 }] },
  { id: 'SPINOSAURUS;4', name: '[Lvl {LVL}] Spinosaurus', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'SPINE_FOSSIL', qty: 1 }, { id: 'FLAWLESS_AQUAMARINE_GEM', qty: 1 }] },
  { id: 'STARFALL_SEASONING', name: 'Starfall Seasoning', duration: 64800, count: 1, hotm: 2, inputs: [{ id: 'TREASURITE', qty: 16 }, { id: 'STARFALL', qty: 64 }] },
  { id: 'TITANIUM_ARTIFACT', name: 'Titanium Artifact', duration: 129600, count: 1, hotm: 4, inputs: [{ id: 'REFINED_TITANIUM', qty: 12 }, { id: 'TITANIUM_RING', qty: 1 }] },
  { id: 'TITANIUM_BELT', name: 'Titanium Belt', duration: 16200, count: 1, hotm: 3, inputs: [{ id: 'REFINED_TITANIUM', qty: 1 }, { id: 'REFINED_MINERAL', qty: 16 }, { id: 'MITHRIL_BELT', qty: 1 }] },
  { id: 'TITANIUM_CLOAK', name: 'Titanium Cloak', duration: 16200, count: 1, hotm: 3, inputs: [{ id: 'MITHRIL_CLOAK', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 1 }, { id: 'REFINED_MINERAL', qty: 16 }] },
  { id: 'TITANIUM_DRILL_1', name: 'Titanium Drill DR-X355', duration: 14400, count: 1, hotm: 5, inputs: [{ id: 'FUEL_TANK', qty: 1 }, { id: 'DRILL_ENGINE', qty: 1 }, { id: 'REFINED_MITHRIL', qty: 8 }, { id: 'REFINED_TITANIUM', qty: 8 }, { id: 'GOLDEN_PLATE', qty: 6 }] },
  { id: 'TITANIUM_DRILL_2', name: 'Titanium Drill DR-X455', duration: 30, count: 1, hotm: 5, inputs: [{ id: 'MITHRIL_PLATE', qty: 5 }, { id: 'REFINED_TITANIUM', qty: 12 }, { id: 'REFINED_DIAMOND', qty: 10 }, { id: 'TITANIUM_DRILL_1', qty: 1 }] },
  { id: 'TITANIUM_DRILL_3', name: 'Titanium Drill DR-X555', duration: 30, count: 1, hotm: 5, inputs: [{ id: 'REFINED_DIAMOND', qty: 20 }, { id: 'ENCHANTED_IRON_BLOCK', qty: 2 }, { id: 'PLASMA', qty: 20 }, { id: 'TITANIUM_DRILL_2', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 16 }, { id: 'MITHRIL_PLATE', qty: 10 }] },
  { id: 'TITANIUM_DRILL_4', name: 'Titanium Drill DR-X655', duration: 30, count: 1, hotm: 6, inputs: [{ id: 'GEMSTONE_MIXTURE', qty: 16 }, { id: 'FLAWLESS_RUBY_GEM', qty: 1 }, { id: 'MITHRIL_PLATE', qty: 10 }, { id: 'REFINED_TITANIUM', qty: 32 }, { id: 'CORLEONITE', qty: 30 }, { id: 'TITANIUM_DRILL_3', qty: 1 }, { id: 'REFINED_DIAMOND', qty: 5 }] },
  { id: 'TITANIUM_DRILL_ENGINE', name: 'Titanium-Plated Drill Engine', duration: 30, count: 1, hotm: 5, inputs: [{ id: 'DRILL_ENGINE', qty: 2 }, { id: 'MITHRIL_DRILL_ENGINE', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 8 }] },
  { id: 'TITANIUM_FUEL_TANK', name: 'Titanium-Infused Fuel Tank', duration: 30, count: 1, hotm: 5, inputs: [{ id: 'REFINED_DIAMOND', qty: 5 }, { id: 'REFINED_TITANIUM', qty: 10 }, { id: 'FUEL_TANK', qty: 5 }, { id: 'MITHRIL_FUEL_TANK', qty: 1 }] },
  { id: 'TITANIUM_GAUNTLET', name: 'Titanium Gauntlet', duration: 16200, count: 1, hotm: 3, inputs: [{ id: 'REFINED_MINERAL', qty: 16 }, { id: 'MITHRIL_GAUNTLET', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 1 }] },
  { id: 'TITANIUM_LANTERN', name: 'Titanium Lantern', duration: 14400, count: 1, hotm: 5, inputs: [{ id: 'MITHRIL_LANTERN', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 2 }, { id: 'ENCHANTED_EMERALD_BLOCK', qty: 1 }] },
  { id: 'TITANIUM_NECKLACE', name: 'Titanium Necklace', duration: 16200, count: 1, hotm: 3, inputs: [{ id: 'REFINED_TITANIUM', qty: 1 }, { id: 'MITHRIL_NECKLACE', qty: 1 }, { id: 'REFINED_MINERAL', qty: 16 }] },
  { id: 'TITANIUM_RELIC', name: 'Titanium Relic', duration: 259200, count: 1, hotm: 5, inputs: [{ id: 'TITANIUM_ARTIFACT', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 20 }] },
  { id: 'TITANIUM_RING', name: 'Titanium Ring', duration: 72000, count: 1, hotm: 3, inputs: [{ id: 'TITANIUM_TALISMAN', qty: 1 }, { id: 'REFINED_TITANIUM', qty: 6 }] },
  { id: 'TITANIUM_TALISMAN', name: 'Titanium Talisman', duration: 50400, count: 1, hotm: 2, inputs: [{ id: 'REFINED_TITANIUM', qty: 2 }] },
  { id: 'TITANIUM_TESSERACT', name: 'Titanium Tesseract', duration: 21600, count: 1, hotm: 3, inputs: [{ id: 'ENCHANTED_LAPIS_LAZULI', qty: 16 }, { id: 'REFINED_TITANIUM', qty: 1 }] },
  { id: 'TUNGSTEN_KEY', name: 'Tungsten Key', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'ENCHANTED_TUNGSTEN', qty: 192 }, { id: 'BEJEWELED_HANDLE', qty: 1 }] },
  { id: 'TUNGSTEN_KEYCHAIN', name: 'Tungsten Regulator', duration: 64800, count: 1, hotm: 8, inputs: [{ id: 'PERFECT_OPAL_GEM', qty: 1 }, { id: 'FUEL_TANK', qty: 5 }, { id: 'TUNGSTEN_PLATE', qty: 5 }] },
  { id: 'TUNGSTEN_PLATE', name: 'Tungsten Plate', duration: 10800, count: 1, hotm: 7, inputs: [{ id: 'GLACITE_AMALGAMATION', qty: 1 }, { id: 'REFINED_TUNGSTEN', qty: 4 }] },
  { id: 'TYRANNOSAURUS;4', name: '[Lvl {LVL}] T-Rex', duration: 604800, count: 1, hotm: 7, inputs: [{ id: 'FOOTPRINT_FOSSIL', qty: 1 }, { id: 'FLAWLESS_ONYX_GEM', qty: 1 }] },
  { id: 'UMBER_KEY', name: 'Umber Key', duration: 30, count: 1, hotm: 7, inputs: [{ id: 'BEJEWELED_HANDLE', qty: 1 }, { id: 'ENCHANTED_UMBER', qty: 192 }] },
  { id: 'UMBER_PLATE', name: 'Umber Plate', duration: 10800, count: 1, hotm: 7, inputs: [{ id: 'REFINED_UMBER', qty: 4 }, { id: 'GLACITE_AMALGAMATION', qty: 1 }] },
  { id: 'WILL_O_WISP', name: 'Will-o\'-wisp', duration: 86400, count: 1, hotm: 10, inputs: [{ id: 'GLACITE_LANTERN', qty: 1 }, { id: 'CAGED_WISP', qty: 1 }, { id: 'PERFECT_PLATE', qty: 1 }, { id: 'EVERBURNING_FLAME', qty: 1 }, { id: 'ENCHANTED_EMERALD_BLOCK', qty: 8 }] },
]
